import datetime
import decimal
import os
import re

import pytest
from django.db import IntegrityError, connections

from django_migrations_ci import django
from django_migrations_ci.backends import oracle

pytestmark = pytest.mark.skipif(
    os.getenv("DATABASES_MODULE") != "oracle",
    reason="Oracle backend tests.",
)

SCHEMA = [
    # The child table name sorts before its parent.
    """
    CREATE TABLE a_child (
        id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        parent_id NUMBER(19) NOT NULL,
        label NVARCHAR2(20)
    )
    """,
    """
    CREATE TABLE z_parent (
        id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 3)
            PRIMARY KEY,
        name NVARCHAR2(100) NOT NULL,
        bio NCLOB,
        data NCLOB CHECK (data IS JSON),
        photo BLOB,
        score BINARY_DOUBLE,
        price NUMBER(38, 10),
        born DATE,
        created TIMESTAMP(9),
        created_tz TIMESTAMP WITH TIME ZONE,
        duration INTERVAL DAY(9) TO SECOND(6),
        period INTERVAL YEAR TO MONTH,
        code CHAR(3),
        hash RAW(16),
        secret NUMBER INVISIBLE,
        doubled AS (price * 2)
    )
    """,
    """
    ALTER TABLE a_child ADD CONSTRAINT a_child_parent_fk FOREIGN KEY (parent_id)
    REFERENCES z_parent (id) DEFERRABLE INITIALLY DEFERRED
    """,
    "CREATE INDEX a_child_label_idx ON a_child (label)",
    "CREATE UNIQUE INDEX z_parent_name_idx ON z_parent (LOWER(name))",
    "CREATE SEQUENCE custom_seq START WITH 100 INCREMENT BY 5",
    "CREATE VIEW parent_names AS SELECT id, name FROM z_parent WHERE name LIKE 'P%'",
    """
    CREATE FUNCTION double_it(x NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN x * 2;
    END;
    """,
    # Changes loaded data if it fires while loading.
    """
    CREATE TRIGGER a_child_bang BEFORE INSERT ON a_child FOR EACH ROW
    BEGIN
        :new.label := :new.label || '!';
    END;
    """,
    """
    CREATE TRIGGER z_parent_disabled BEFORE UPDATE ON z_parent FOR EACH ROW
    BEGIN
        :new.name := 'updated';
    END;
    """,
    "ALTER TRIGGER z_parent_disabled DISABLE",
    "COMMENT ON TABLE z_parent IS 'it''s a parent'",
    "COMMENT ON COLUMN z_parent.name IS 'the name'",
    # Dropped tables go to the recycle bin.
    "CREATE TABLE doomed (id NUMBER)",
    "DROP TABLE doomed",
]

LONG_TEXT = "çãõ€ 🚌 " * 5000


def _create_schema(connection):
    connection.ensure_connection()
    with connection.connection.cursor() as cursor:
        for statement in SCHEMA:
            cursor.execute(statement)
        cursor.execute(
            """
            INSERT INTO z_parent (
                name, bio, data, photo, score, price, born, created, created_tz,
                duration, period, code, hash, secret
            ) VALUES (
                :name, :bio, :data, :photo, BINARY_DOUBLE_NAN, :price,
                TO_DATE('1999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
                TIMESTAMP '2024-02-29 23:59:59.123456789',
                TO_TIMESTAMP_TZ(
                    '2024-03-10 01:30:00.5 America/Sao_Paulo',
                    'YYYY-MM-DD HH24:MI:SS.FF TZR'
                ),
                :duration, INTERVAL '-3-7' YEAR TO MONTH, 'ab', :hash, 42
            )
            """,
            name="Parent 'one'",
            bio=LONG_TEXT,
            data='{"a": [1, 2.5, null], "s": "x\'y"}',
            photo=bytes(range(256)) * 200,
            price=decimal.Decimal("-1234567890123456789012345678.0123456789"),
            # python-oracledb stores it with mixed signs.
            duration=datetime.timedelta(days=-3, seconds=5, microseconds=7),
            hash=b"\x00\xff",
        )
        cursor.execute(
            "INSERT INTO z_parent (name, bio) VALUES ('Parent two', EMPTY_CLOB())"
        )
        cursor.execute("INSERT INTO a_child (parent_id, label) VALUES (13, 'c1')")
        cursor.execute("INSERT INTO a_child (parent_id, label) VALUES (10, 'c2')")
        connection.connection.commit()


def _read_dump(path):
    # Identities start after the loaded rows, which changes their START WITH.
    content = path.read_text()
    return re.sub(r"(AS IDENTITY .*?)START WITH \d+", r"\1START WITH N", content)


def _fetchall(connection, query):
    with connection.cursor() as cursor:
        cursor.execute(query)
        return cursor.fetchall()


def test_dump_and_load(tmp_path):
    connection = connections["default"]
    django.create_test_db(connection, verbosity=0)
    with django.test_db(connection):
        _create_schema(connection)
        oracle.dump(connection, tmp_path / "dump")

    django.create_test_db(connection, verbosity=0)
    with django.test_db(connection):
        oracle.load(connection, (tmp_path / "dump").read_text())
        oracle.dump(connection, tmp_path / "dump_again")

        assert _read_dump(tmp_path / "dump_again") == _read_dump(tmp_path / "dump")
        assert (
            _fetchall(
                connection,
                "SELECT object_name, status FROM user_objects "
                "WHERE status <> 'VALID' OR object_name LIKE 'BIN$%'",
            )
            == []
        )
        assert _fetchall(connection, "SELECT id, label FROM a_child ORDER BY id") == [
            (1, "c1!"),
            (2, "c2!"),
        ]
        # NCLOB lengths count UTF-16 code units.
        assert _fetchall(
            connection, "SELECT DBMS_LOB.GETLENGTH(bio) FROM z_parent ORDER BY id"
        ) == [(len(LONG_TEXT.encode("utf-16-le")) // 2,), (0,)]

        # Identities continue after the loaded rows.
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO z_parent (name) VALUES ('Parent three')")
            cursor.execute(
                "INSERT INTO a_child (parent_id, label) "
                "SELECT MAX(id), 'c3' FROM z_parent"
            )
        assert _fetchall(connection, "SELECT MAX(id) FROM z_parent") > [(13,)]
        assert _fetchall(connection, "SELECT MAX(id) FROM a_child") == [(3,)]

        # Foreign keys are enforced.
        with pytest.raises(IntegrityError):
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO a_child (parent_id) VALUES (99)")


def test_dump_unsupported_object(tmp_path):
    connection = connections["default"]
    django.create_test_db(connection, verbosity=0)
    with django.test_db(connection):
        with connection.cursor() as cursor:
            cursor.execute("CREATE TABLE t (id NUMBER PRIMARY KEY)")
            cursor.execute("CREATE MATERIALIZED VIEW mv AS SELECT id FROM t")
        with pytest.raises(
            NotImplementedError,
            match=re.escape("Can't dump Oracle objects: MATERIALIZED VIEW MV."),
        ):
            oracle.dump(connection, tmp_path / "dump")


def test_dump_unsupported_column(tmp_path):
    connection = connections["default"]
    django.create_test_db(connection, verbosity=0)
    with django.test_db(connection):
        with connection.cursor() as cursor:
            cursor.execute("CREATE TABLE t (id ROWID)")
        with pytest.raises(
            NotImplementedError,
            match=re.escape("Can't dump Oracle ROWID column T.ID."),
        ):
            oracle.dump(connection, tmp_path / "dump")
