--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: buser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO buser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: buser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: testapp_bus; Type: TABLE; Schema: public; Owner: buser
--

CREATE TABLE public.testapp_bus (
    id bigint NOT NULL,
    plate text NOT NULL
);


ALTER TABLE public.testapp_bus OWNER TO buser;

--
-- Name: testapp_bus_id_seq; Type: SEQUENCE; Schema: public; Owner: buser
--

ALTER TABLE public.testapp_bus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.testapp_bus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: buser
--

INSERT INTO public.django_migrations VALUES (1, 'testapp', '0001_initial', '2022-10-30 15:04:02.828873+00');
INSERT INTO public.django_migrations VALUES (2, 'testapp', '0002_create_bus', '2022-10-30 15:04:02.837662+00');


--
-- Data for Name: testapp_bus; Type: TABLE DATA; Schema: public; Owner: buser
--

INSERT INTO public.testapp_bus VALUES (1, 'BUS3R');


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: buser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 2, true);


--
-- Name: testapp_bus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: buser
--

SELECT pg_catalog.setval('public.testapp_bus_id_seq', 1, true);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: buser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: testapp_bus testapp_bus_pkey; Type: CONSTRAINT; Schema: public; Owner: buser
--

ALTER TABLE ONLY public.testapp_bus
    ADD CONSTRAINT testapp_bus_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

